export const THEME = {
  colors: {
    sage: '#5A664D',
    sageDark: '#434D39',
    sageDeep: '#262E20',
    sageLight: '#7A8A6D',
    sageBg: '#E8EFE3',
    sageSurface: '#F2F7EE',
    sageMuted: '#CBD7C3',
    beige: '#E8EFE3',
    ivory: '#F2F7EE',
    warm: '#DFE7DA',
    taupe: '#BFCBB6',
    taupeLight: '#E2EAD8',
    taupeDark: '#5A664D',
    gold: '#C5A059',
    goldLight: '#DFC48A',
    goldDark: '#9E7E38',
    dark: '#1F1B18',
    charcoal: '#2E2824',
    muted: '#5A664D',
  },
  brand: {
    name: 'AISHKA CLOTHING',
    shortName: 'AISHKA',
    logo: '/logo-transparent.png',
    logoLight: '/logo-transparent-light.png',
    logoBadge: '/logo-emblem.png',
    tagline: 'TIMELESS • MODEST • ELEGANT',
    subCopy: 'Everyday casual wear with comfort, simplicity, and effortless style',
    whatsapp: '+919876543210',
    whatsappDisplay: '+91 98765 43210',
    instagram: '@aishkaclothing',
    instagramUrl: 'https://instagram.com/aishkaclothing',
    email: 'contact@aishkaclothing.com',
    address: 'Studio & Atelier Visits: By Appointment Only',
    hours: 'Monday – Saturday: 10:30 AM – 7:30 PM | Sunday: Closed',
  }
};
